// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDva81Ozgbk04e8pVieZHQSa7qS0kaFCuo',
    appId: '1:891756262031:web:5afc474d1569d3fb0576fa',
    messagingSenderId: '891756262031',
    projectId: 'employeemanagment-15437',
    authDomain: 'employeemanagment-15437.firebaseapp.com',
    storageBucket: 'employeemanagment-15437.firebasestorage.app',
    measurementId: 'G-Z82ZMYRJEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiR_ek-gWFwPnwFsBEfLj5HqTQO81XQ84',
    appId: '1:891756262031:android:bf23f83eea41c09d0576fa',
    messagingSenderId: '891756262031',
    projectId: 'employeemanagment-15437',
    storageBucket: 'employeemanagment-15437.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzwP8Xc-FayTDRtzw1LoUbb_hyc9LI1vA',
    appId: '1:891756262031:ios:855345980b6714330576fa',
    messagingSenderId: '891756262031',
    projectId: 'employeemanagment-15437',
    storageBucket: 'employeemanagment-15437.firebasestorage.app',
    iosBundleId: 'com.example.employeemanagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzwP8Xc-FayTDRtzw1LoUbb_hyc9LI1vA',
    appId: '1:891756262031:ios:855345980b6714330576fa',
    messagingSenderId: '891756262031',
    projectId: 'employeemanagment-15437',
    storageBucket: 'employeemanagment-15437.firebasestorage.app',
    iosBundleId: 'com.example.employeemanagment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDva81Ozgbk04e8pVieZHQSa7qS0kaFCuo',
    appId: '1:891756262031:web:c850ed5c9b1464fd0576fa',
    messagingSenderId: '891756262031',
    projectId: 'employeemanagment-15437',
    authDomain: 'employeemanagment-15437.firebaseapp.com',
    storageBucket: 'employeemanagment-15437.firebasestorage.app',
    measurementId: 'G-NYECV55DD3',
  );
}
